### ISSUE TITLE
undefined: mqstrerror

### ISSUE THREAD

**Issue by BluePixSE** [ibm-messaging/mq-golang#149]
Hi,

I have a MQ 9.2.0.0, trying to install mq-golang v5.1.1 with go 1.10.4.
But I got a compiler error when trying to run go install;

$ go install ./src/github.com/ibm-messaging/mq-golang/ibmmq
\# github.com/ibm-messaging/mq-golang/ibmmq
src/github.com/ibm-messaging/mq-golang/ibmmq/mqi.go:124: undefined: mqstrerror

Any easy way out? :-)

**Comment by ibmmqmet** [comment]
Update to a later compiler - 1.13 or 1.14. Some of the module support in the compiler became more integrated at that point so it's what I've been using to develop against. It looks like the mqistr file will only build on 1.13 (though there's no specific reason for that and I may remove the directive that enforces it) but the later compilers are definitely preferred anyway.

**Comment by BluePixSE** [comment]
Thanks! 
For 1.13.3 it works great.
